### ISSUE TITLE
V24: ensure dev bundle isn't included in add-on

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/addon-starter-flow#279]
**Describe your motivation**
V24 add-on skeleton shouldn't generate a dev bundle because it's not an application, it's an add-on
**Describe the solution you'd like**
Do not generate dev bundle
**Describe alternatives you've considered**

**Comment by Legioth** [comment]
It might be fine that a bundle is created since it helps speed up development of the add-on itself.

We should just make sure that the bundle is not included in the stuff that would be uploaded to Directory. It might potentially works in that way automatically since it might only pick sources from e.g. `src/main/java` and not from `src/main/dev-bundle` (I haven't tested).

**Comment by Artur-** [comment]
The files in `src/main/dev-bundle` are never included in a jar or war

**Comment by mshabarov** [comment]
Can we close this issue or do we expect something to be fixed in Flow? I don't see what we should do/fix.

**Comment by mshabarov** [comment]
~We don't have a branch for V24 by the way. I'll make a ticket.~
