### ISSUE TITLE
Create V24 branch and upgrade project to latest V24.0

### ISSUE THREAD

**Issue by mshabarov** [vaadin/addon-starter-flow#280]

**Comment by mcollovati** [comment]
As discussed in #281, starting with Vaadin 24, it would probably be better to have a different structure for the add-on template, to prevent dependencies scope leaks without dirty hacks.

The proposed structure is the same as we got in Vaadin 8 archetypes, with a multimodule project composed by the add-on and a test/demo module.
This way, the add-on will define all Vaadin dependencies as `provided`, and the demo/test module can use compile scoped artifacts if needed.
On the other hand, the multimodule structure may be less simple to start with.

The solution with a single module proposed in the PR is a bit messy and probably prone to deployment mistakes, as the developer should remember to switch between profiles.

I think we should promote the production of a clean artifact, even if the development setup may be a bit more complex, so I would go with the multimodule.

A separated topic is add-on migration: should we provide documentation for migration of modules created with the V23 template?
There are no significant changes to apply (version updates and some minor jetty plugin configuration), but the V23 templates suffers from the scope leak, and we should perhaps provide suggestions to fix it. The questions are where to put this documentation (Upgrade guide on documentation website?) and what kind of changes to propose (handling scope with profiles as in #281? migrate to multimodule?).

Pinging again @samie @mstahv @tltv for further discussion.

**Comment by mstahv** [comment]
Moving tests related to the add-on to a different modules sounds quite wrong to me. How should the development workflow work then 🤷‍♂️

**Comment by mstahv** [comment]
Why having a direct dependency from add-on to vaadin-core or flow-server is suddenly seen as an issue?

**Comment by mcollovati** [comment]
Right, `vaadin-core` or `flow-server` may not be a problem, as the user project should always import `vaadin-bom` or explicitly define a dependency to `vaadin-core` or `vaadin`.
A dependency to `vaadin` in the add-on may bring in dependencies to unused components, but this may not happen so frequently.

With MPR for Vaadin 24 there were issues with V8 add-ons with compile scope dependency to `vaadin-server`, but the reason was that we have a different server artifact name for Jakarta EE 10. However, projects using V8 add-ons are forced to explicitly add exclusion of `vaadin-server` on all used add-ons because of the compile scope. Anyway, this is restricted to the particular MPR + V24 use case. We hopefully won't see similar issues with Flow in the future.

If we want to continue with the single module, I would at least change the `vaadin-core` scope to `test` and add a compile dependency to `flow-server`, as I can see no advantages in having the `vaadin-core` as a compile dependency.
And in the current template `vaadin-core` is added only to be able to run the test view and the integration tests

**Comment by mcollovati** [comment]
I had memories of some issues with license checking caused by an add-on with a dependency to `vaadin`, but after checking again, it turned out it was something wrong with the license checker.
So, it turns out that a compile dependency to `vaadin-core` should not be problematic.

**Comment by mcollovati** [comment]
The v24 branch is now pushed, and it will be the default branch
